### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by B0elena** [B0elena/furima_28818#10]
自身のフリマアプリのURL
https://furima-28818.herokuapp.com/
Basic認証のIDとパスワード
ID:elena
パスワード:ccd1012
出品者用のメールアドレスとパスワード
メールアドレス:md@gmail.com
パスワード:ccd1012
購入者用のメールアドレスとパスワード
メールアドレス:mdd@gmail.com
パスワード:ccd1012
購入用カードの番号・期限・セキュリティコード
4242424242424242
3.23
123

**Comment by tech-oa** [comment]
B0elenaさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○Basic認証が実装できていないようです。
IDとパスワードを入力してクリック後、また同じ入力フォームが表示されてしまいますので、修正をお願いします。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by B0elena** [comment]
申し訳ありません。パスワードを間違えて記載してしまいました。正しくはこちらになります。よろしくお願いします。

自身のフリマアプリのURL
https://furima-28818.herokuapp.com/
Basic認証のIDとパスワード
ID:elena
パスワード:1124
出品者用のメールアドレスとパスワード
メールアドレス:md@gmail.com
パスワード:ccd1012
購入者用のメールアドレスとパスワード
メールアドレス:mdd@gmail.com
パスワード:ccd1012
購入用カードの番号・期限・セキュリティコード
4242424242424242
3.23
123

**Comment by tech-oa** [comment]
B0elenaさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○購入が完了したら、トップページまたは購入完了ページに遷移する
こちら、購入をクリックした後、一度入力内容がリセットされた画面に移り、その後トップページに遷移しています。購入後、すぐにトップページあるいは購入完了ページに遷移するよう修正をお願いします。

Basic認証に関しては、正しいパスワードを入力後、トップページに遷移できていました。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by B0elena** [comment]
修正致しましたので、再度挙動確認よろしくお願いします。

自身のフリマアプリのURL
https://furima-28818.herokuapp.com/
Basic認証のIDとパスワード
ID:elena
パスワード:1124
出品者用のメールアドレスとパスワード
メールアドレス:md@gmail.com
パスワード:ccd1012
購入者用のメールアドレスとパスワード
メールアドレス:mdd@gmail.com
パスワード:ccd1012
購入用カードの番号・期限・セキュリティコード
4242424242424242
3.23
123

**Comment by tech-oa** [comment]
B0elenaさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by B0elena** [comment]
ありがとうございます！！
